theme: minima
title: Kade's Test Website
Author: Kade
description: This is my test website.
social_links:
    - { platform: instagram,  user_url: "https://www.instagram.com/latoncompany/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/janae-talbott-561024b/" }
    - { platform: facebook, user_url: "https://www.facebook.com/janae.talbott" }
